### ISSUE TITLE
2D shaders don't work, instructions to fix them aren't clear.

### ISSUE THREAD

**Issue by ghost** [gamedevserj/Shader-Graph-Experiments#2]
"_CameraOpaqueTexture does not work anymore in 2D. Instead, you need to use the _CameraSortingLayerTexture tag."
-Where do I find "_CameraSortingLayerTexture" so I can enable it?

"Use _CameraSortingLayerTexture tag, remove the "Exposed" checkmark."
-Where is this "exposed" checkmark I'm supposed to disable?

Basically, I don't know 'where' anything is, because I'm new. Telling people to 'just change these values and it should work' isn't enough information, you have to actually tell them where this stuff is so they can change it.

**Comment by gamedevserj** [comment]
Both of the things mentioned are inside the actual shader graphs. 
Since you're new I suggest watching some tutorials on shader graph to understand it better. This one could be a good start https://www.youtube.com/watch?v=gJMeSkolnw4

The repository is not meant to be a tutorial for complete beginners.
